### ISSUE TITLE
filterContent Not Called

### ISSUE THREAD

**Issue by attila226** [Dhaulagiri/ember-cli-twitter-typeahead#7]
When I run the sample app, the filterContent function is never called. In fact I can remove the function from the model, and there's no errors.

The documentation isn't very clear, so perhaps this is a misunderstanding of it's use, but I'm assuming that it should be called at some point.

**Comment by daltonamitchell** [comment]
Had the same issue. Reading through the source I found a `valueToken` prop that's not mentioned but seems necessary. It specifies the property to pass into your filter. Try adding `valueToken='name'` as an example if you're filtering by name.

**Comment by Gast** [comment]
Had the same issue to. Try :
 {{twitter-typeahead
...
_filterContent=controllerMethod
...
 }}

**Comment by Dhaulagiri** [comment]
Yes, you must specify `valueToken`
